/*
 * Copyright 2013 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package de.schildbach.wallet.integration.android;

/**
 * Describes a listener which receives events from a {@link BitcoinPaymentChannelManager}
 */
public interface ChannelListener {
    /**
     * Enumerates the reasons a channel may be closed or fail to open.
     * Mostly a copy of the same enum from bitcoinj PaymentChannelCloseException.CloseReason.
     */
    public enum CloseReason {
        /** Wallet app gave us a reason code we can't map to anything in this enum. */
        UNKNOWN(-2),

        /** The wallet app couldn't be found: did you call prepare? If so the user may have uninstalled it. */
        NO_WALLET_APP(-1),

        /** We could not find a version which was mutually acceptable with the client/server */
        NO_ACCEPTABLE_VERSION(0),
        /** Generated by a client when the server attempted to lock in our funds for an unacceptably long time */
        TIME_WINDOW_TOO_LARGE(1),
        /** Generated by a client when the server requested we lock up an unacceptably high value */
        SERVER_REQUESTED_TOO_MUCH_VALUE(2),

        // Values after here indicate its probably possible to try reopening channel again

        /** The app requested that the channel be closed. */
        CLIENT_REQUESTED_CLOSE(3),

        /**
         * <p>The server closed the channel. For a client, this usually indicates that we should try again if we need
         * to continue paying (either opening a new channel or continuing with the same one depending on the server's
         * preference)</p>
         */
        SERVER_REQUESTED_CLOSE(4),

        /** Remote side sent an ERROR message */
        REMOTE_SENT_ERROR(5),
        /** Remote side sent a message we did not understand */
        REMOTE_SENT_INVALID_MESSAGE(6),

        /** The connection was closed without an ERROR/CLOSE message */
        CONNECTION_CLOSED(7);

        private int code;
        CloseReason(int code) { this.code = code; }

        public static CloseReason from(int reason) {
            for (CloseReason r : values()) {
                if (r.ordinal() == reason) return r;
            }
            return UNKNOWN;
        }
    }

	/**
	 * <p>Called to indicate the channel has successfully been opened and payments/messages can be submitted.</p>
	 *
	 * <p>This method may be called more than once if the channel is interrupted and later reconnected to, however,
	 * because reconnection will always use the same channel, contractHash will not change for any one given
	 * {@link BitcoinPaymentChannelManager}.</p>
	 *
	 * @param contractHash The bitcoin hash of the contract transaction which locks in the channel
	 */
	public void channelOpen(byte[] contractHash);

	/**
	 * <p>Called when the connection with the wallet apphas been interrupted. Reconnection may happen automatically, or
	 * it may happen on the next request to the {@link BitcoinPaymentChannelManager} (though that request will fail).
	 * When reconnection either succeeds or fails, channelOpen or channelClosedOrNotOpened will be called.</p>
	 *
	 * <p>Note that when the reconnection attempt occurs, a new handshake with the server will be attempted, which means
	 * the connection to the server must be closed as well.</p>
	 */
	public void channelInterrupted();

	/**
	 * Called to indicate the channel has been closed or opening the channel failed for some reason (rejected, wallet
	 * app not installed, unable to make a connection, etc). The associated {@link BitcoinPaymentChannelManager} is no
	 * longer valid. The connection to the server should be closed.
	 */
	public void channelClosedOrNotOpened(CloseReason reason);

	/** Called when the given protobuf (in the form of an encoded byte array) should be sent to the server (in order) */
	void sendProtobuf(byte[] protobuf);
}
